# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# https://devblogs.microsoft.com/dotnet/using-dependabot-to-manage-dotnet-sdk-updates/
# https://learn.microsoft.com/en-us/dotnet/core/tools/global-json

version: 2
updates:
- package-ecosystem: "dotnet-sdk"
  directories:
  - "/AppControl Manager/"
  - "/Harden-Windows-Security Module/"
  - "/Harden Windows Security App (WIP)/"
  schedule:
    interval: "weekly"
    day: "tuesday"
  labels:
  - "Dependabot"
- package-ecosystem: "nuget"
  directories:
  - "/AppControl Manager/"
  - "/Harden-Windows-Security Module/"
  - "/Harden Windows Security App (WIP)/"
  schedule:
    interval: "daily"
    time: "07:30"
    timezone: "Israel"
  labels:
  - "Dependabot"
- package-ecosystem: "github-actions"
  directory: "/"
  commit-message:
    prefix: "actions"
  labels: [ 'chore ' ]
  schedule:
    interval: "cron"
    cronjob: "0 7 * * *"
    timezone: "Europe/Paris"
  groups:
    actions-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
- package-ecosystem: "cargo"
  directories:
  - "/AppControl Manager/eXclude/ResourceValidator/"
  - "/AppControl Manager/eXclude/Rust WMI Interop/Device Guard/Library/"
  - "/AppControl Manager/eXclude/Rust WMI Interop/Device Guard/Program/"
  - "/AppControl Manager/eXclude/Rust WMI Interop/Microsoft Defender/Program/"
  - "/AppControl Manager/eXclude/Rust WMI Interop/Microsoft Defender/Library/"
  - "/AppControl Manager/eXclude/Rust WMI Interop/Microsoft Defender/Printing raw data with types/"
  schedule:
    interval: "daily"
    time: "07:30"
    timezone: "Israel"
